options:
  min-master-count:
    description: |
      Minimum number of master nodes
    default: 1
    type: int
  custom-config:
    description: |
      String representation of custom elasticsearch.yml configs
    type: string
    default: ""
  node-type:
    description: |
      Type of elasticsearch node. Choices are 'data', 'master', 'ingest', 'tribe', 'all'.
    type: string
    default: 'all'
  firewall_enabled:
    description: |
      this option will enable or disable the ufw. By default this is set to
      'false' since the firewall is never enabled when a machine or container
      is created with juju. Set to 'true' to enable firewall. Once enabled
      rules will be added when another charm has a relation with elasticsearch.
      This charm will be able to access elasticsearch on port 9200, while
      all the other traffice to that port will be blocked. Enabling the firewall
      will also allow port 22 from anywhere.
    type: boolean
    default: false
  cluster-name:
    description: |
      This sets the elasticsearch cluster name. This name is then added to the
      elasticsearch.yml file
    type: string
    default: "elasticsearch"
