#!/usr/local/sbin/charm-env python

import json
import sys
import urllib3

from base64 import b64decode

from charmhelpers.core.hookenv import (
    action_fail,
    action_get,
    action_set,
    status_set,
)


def update_cluster_global_settings(settings):
    """Update the cluster global settings
    """
    ctxt = {'headers': {'Content-Type': 'application/json'},
            'method': 'PUT',
            'url': "http://localhost:9200/_cluster/settings",
            'body': json.dumps(settings),
    }

    http = urllib3.PoolManager()
    r = http.request(**ctxt)
    return r.data.decode()


def update_index_settings(index, settings):
    """Update the settings for an index
    """
    ctxt = {'headers': {'Content-Type': 'application/json'},
            'method': 'PUT',
            'url': "http://localhost:9200/{}/_settings".format(index),
            'body': json.dumps(settings),
    }

    http = urllib3.PoolManager()
    r = http.request(**ctxt)
    return r.data.decode()


def get_indices():
    """Return a list of indices
    """
    ctxt = {'headers': {'Content-Type': 'application/json'},
            'method': 'GET',
            'url': "http://localhost:9200/_cat/indices?h=index"
    }
    http = urllib3.PoolManager()
    r = http.request(**ctxt)
    return r.data.decode().split()


if __name__ == "__main__":
    index = action_get('index-name')
    settings_json = b64decode(action_get('settings-json'))
    try:
        settings_json = json.loads(settings_json)
    except json.JSONDecodeError:
        msg = "INVALID JSON"
        action_set({'settings-update-result': msg})
        action_fail(msg)

    if index == "*":
        for i in get_indices().split():
            result = update_index_settings(i, settings_json)
            action_set({'settings-update-{}'.format(i): result})
    elif index == "cluster":
        result = update_cluster_global_settings(settings_json)
        action_set({'settings-update-{}'.format(index): result})
    else:
        result = update_index_settings(index, settings_json)
        action_set({'settings-update-{}'.format(index): result})

    status_set('active', "Settings update complete")
