options:
  java-opts:
    description: Java Opts
    default: ""
    type: string
  min-master-count:
    description: |
      Minimum number of master nodes
    default: 1
    type: int
  custom-config:
    description: |
      String representation of custom elasticsearch.yml configs
    type: string
    default: ""
  node-type:
    description: |
      Type of elasticsearch node. Choices are 'data', 'master', 'ingest', 'coordinating', 'all'.
    type: string
    default: 'all'
  xpack-security-enabled:
    description: |
      Enable xpack security.
    default: true
    type: boolean
  cluster-name:
    description: |
      This sets the elasticsearch cluster name. This name is then added to the
      elasticsearch.yml file
    type: string
    default: "elasticsearch"
